export const experience = [
    {
        id: "tg-intern",
        role: "AI/ML and Computer Vision Intern",
        company: "TechtoGreen Drone & Robotics Private Limited",
        period: "Dec 2024 — May 2026",
        description: "Deployed edge AI models and engineered dual-model vision pipelines using VGGT monocular depth estimation and YOLO segmentation. Integrated YDLIDAR G2 sensors and managed MAVLink telemetry via FastAPI.",
    },
    {
        id: "ml-tech",
        role: "Technical Team Member",
        company: "The Machine Learning CLUB VITAP",
        period: "Sep 2024 — May 2025",
        description: "Collaborating on AI initiatives and technical frameworks within the VIT-AP University developer community.",
    },
    {
        id: "ml-project",
        role: "Project Team Member",
        company: "The Machine Learning CLUB VITAP",
        period: "Oct 2023 — Sep 2024",
        description: "Contributed to project bootcamps and developed applications utilizing Tkinter and Pandas.",
    },
];

export const projects = [
    {
        title: "Autonomous Precision Agriculture & Telemetry",
        subtitle: "Real-time crop disease detection pipeline",
        description: "Engineered a YOLO and OpenCV pipeline processing live drone feeds. Integrated MAVLink telemetry, VITS offline TTS, and a multi-threaded PyQt6 GUI.",
        link: "",
        categoryIds: ["Computer Vision", "Applied Research"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "Automated Agronomic Reporting Engine",
        subtitle: "FastAPI PDF generation system",
        description: "Developed a dynamic PDF report generation system with fpdf2, featuring i18n for English/Telugu and custom text shaping for cross-platform rendering.",
        link: "",
        categoryIds: ["Applied Research"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "Warehouse Inventory & Occupational Safety",
        subtitle: "YOLO-based tracking and compliance",
        description: "Built a real-time SKU counting system with custom NMS. Developed safety pipelines combining YOLOv8 and MediaPipe Pose for ergonomic posture and hardhat compliance.",
        link: "",
        categoryIds: ["Computer Vision", "Applied Research"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "Autonomous Aquatic Surface Robot (TGWV1)",
        subtitle: "Vision and navigation pipeline",
        description: "Engineered YOLO-based obstacle classification and integrated a YDLIDAR G2 sensor via custom C++ application for 360-degree point cloud data.",
        link: "",
        categoryIds: ["Computer Vision", "Applied Research", "Hardware"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "3D Scene Reconstruction & Vegetation Analysis",
        subtitle: "Monocular depth and segmentation",
        description: "Combined VGGT depth estimation and YOLO instance segmentation. Implemented Trimesh point-cloud generation to convert predictions into interactive GLB environments.",
        link: "",
        categoryIds: ["Computer Vision", "Applied Research"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "SentinelHelm Intelligent Surveillance",
        subtitle: "AI security and threat detection",
        description: "Integrated YOLO weapon detection and DeepFace facial recognition. Built a Person of Interest tracking pipeline with ArcFace and FAISS vector similarity search.",
        link: "",
        categoryIds: ["Computer Vision", "Applied Research", "Hardware"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "Cross-Modal Spectral & Visual Analysis",
        subtitle: "Unsupervised anomaly detection",
        description: "Applied DBSCAN clustering on FT-IR spectra. Built a custom computer vision feature extractor fusing Hue/Saturation histograms and LBP texture maps.",
        link: "",
        categoryIds: ["Applied Research"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "Visual SLAM & Odometry Engine",
        subtitle: "6-DOF camera pose estimation",
        description: "Developed a monocular VO system with ORB feature extraction and FLANN matching. Built a SLAM architecture using StereoSGBM and Lucas-Kanade optical flow.",
        link: "",
        categoryIds: ["Computer Vision", "Applied Research"],
        relatedExperienceId: "tg-intern",
    },
    {
        title: "PAC 3D",
        subtitle: "Godot Engine Survival Game",
        description: "Engineered a 3D survival game using GDScript with dynamic enemy AI, spatial pathfinding, and state-persistent UI overlays.",
        link: "https://github.com/MLC-VIT-AP/PAC_3D",
        categoryIds: ["Game Development"],
        relatedExperienceId: "ml-project",
    },
    {
        title: "Chakshu",
        subtitle: "AI-driven SIEM Framework",
        description: "Log ingestion and multi-channel protocol threat correlation featuring custom synthetic host telemetry generation.",
        link: "https://github.com/Meehir5907/Chakshu",
        categoryIds: ["Personal"],
        relatedExperienceId: null,
    },
    {
        title: "Sharvara",
        subtitle: "N-Channel Transformer Model",
        description: "PyTorch-based architecture designed for classifying malicious network packets within the CTU-13 dataset.",
        link: "https://github.com/Meehir5907/Sharvara",
        categoryIds: ["Personal"],
        relatedExperienceId: null,
    },
    {
        title: "MemoRe",
        subtitle: "Dual N-Back Engine",
        description: "C++/Qt and QML implementation of the working memory game with dynamic UI components and CMake build configuration.",
        link: "https://github.com/Meehir5907/MemoRe",
        categoryIds: ["Personal"],
        relatedExperienceId: null,
    },
    {
        title: "AR Accessibility Smart Glasses",
        subtitle: "Hardware Prototype",
        description: "Wearable system featuring heads-up captioning, MEMS microphone arrays, and local edge AI processing.",
        link: "",
        categoryIds: ["Computer Vision", "Hardware"],
        relatedExperienceId: null,
    },
];
